language: node_js
sudo: true
node_js:
- '8'
branches:
  only:
  - master
before_install:
- openssl aes-256-cbc -K $encrypted_6f885a4e991a_key -iv $encrypted_6f885a4e991a_iv
  -in ./.travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name 'leekachung'
- git config --global user.email 'leekachung17@gmail.com'
install:
- npm install hexo-cli -g
- npm install --save hexo-deployer-git
- npm install --save-dev hexo-util
- npm install -g yuque-hexo
- npm install hexo-generator-sitemap --save
- npm install hexo-generator-baidu-sitemap --save
- npm install hexo-abbrlink --save
- npm install
script:
- npm run deploy
