# Header
menu:
  Tag: /tags
  Archives: /archives
  Resource: "https://lib.leekachung.cn" 
  Contact:  "mailto:leekachung17@gmail.com"
  
# Content
excerpt_link: More >>
fancybox: true

# Miscellaneous
favicon: /images/favicon.ico